### ISSUE TITLE
Office 2016 CTP install leaves Office 2013 registry entries

### ISSUE THREAD

**Issue by bevanweiss** [bpatra/ExcelDNAWixInstallerLM#17]
I've got a machine that I've installed Office 2016 CTP onto, overwriting Office 2013.  However it appears to have left most of the Office 2013 registry entries (but not all).

With the current oldest first method of detecting Office versions this detects Office 2013, however fails to detect the appropriate bitness of the executable, which then causes a rollback to occur.

I believe that the version detection should be from the most recent backwards, so try to detect 2016 first, and then 2013, then 2010 etc..

I believe this might be possible by just re-ordering in the wxs the version numbers used.  I'll submit a pull request for this shortly.

**Comment by scadorel** [comment]
Hello,

I was also able to reproduce the issue when upgrading office 2010 to 2013.
Several versions of Office could be installed side-by-side, that's why the sample tries to install it on all supported versions but when upgrading, office detection think that the older version is still installed but it is not.
I've made a fix for that. I will provide the PR shortly.
